### ISSUE TITLE
Randomize artists: index out of range

### ISSUE THREAD

**Issue by stanim** [budkin/jam#14]
When I pressed R, i got the following panic:

panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x6c1060, 0xc42000c150)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
main.printSongs(0xa623a0, 0xc42008af20, 0x0, 0x41)
	/home/stani/Labo/go/src/github.com/budkin/jam/ui.go:635 +0x1211
main.updateUI(0xa623a0, 0xc42008af20)
	/home/stani/Labo/go/src/github.com/budkin/jam/ui.go:371 +0x225
main.randomizeArtists(0xa623a0, 0xc42008af20)
	/home/stani/Labo/go/src/github.com/budkin/jam/ui.go:177 +0x14b
main.mainLoop(0xa623a0, 0xc42008af20)
	/home/stani/Labo/go/src/github.com/budkin/jam/ui.go:163 +0x1c7
main.initUI()
	/home/stani/Labo/go/src/github.com/budkin/jam/ui.go:100 +0x122
main.main()
	/home/stani/Labo/go/src/github.com/budkin/jam/main.go:70 +0xb8

**Comment by budkin** [comment]
this is hopefully fixed in master, now all previously unfolded artists are folded after randomizing
