### ISSUE TITLE
Last.fm support

### ISSUE THREAD

**Issue by budkin** [budkin/jam#19]
One of the lacking features that prevent me from using my own player

**Comment by nlamirault** [comment]
I start a new branch.
See: https://github.com/nlamirault/jam/tree/lastfm

**Comment by budkin** [comment]
I think this library will suit our needs
https://github.com/shkh/lastfm-go

**Comment by nlamirault** [comment]
Yes I had taken this one

**Comment by budkin** [comment]
last.fm support should be optional. so the first time the program is launched it should show the user the authUrl link
`authUrl = api.GetAuthTokenUrl (token)`

 if the user follows it and grants permission then `var lastfm bool` should be `true`, if he ignores it and just presses enter, then `false`. Pressing enter should be mandatory either way and stated in a message. At least that's how I imagine it

**Comment by nlamirault** [comment]
I've push LastFM authentication with token (in my repo/branch). If you could make some tests.

**Comment by budkin** [comment]
works almost alright. it does show now playing track, but does not change it on "next track" command

**Comment by budkin** [comment]
and it seems to scrobble to early. the rules is: scrobble the track after 50% of duration of the song has played, but not longer than 4 minutes (scrobble after 4 minutes)

**Comment by budkin** [comment]
I'm working on it

**Comment by budkin** [comment]
Fixed with the new release

**Comment by nlamirault** [comment]
:+1:

**Comment by budkin** [comment]
take a quick look at the changes I made, Nicolas, I don't think they are ideal code

**Comment by nlamirault** [comment]
Works fine for my account. Great job.
