### ISSUE TITLE
Cannot sign-in with 2 factor authentication

### ISSUE THREAD

**Issue by MartijnBraam** [budkin/jam#2]
If I try to login I get this:

```
Email: [email]
Password: [password]
2017/01/26 20:01:29 gpsoauth: 403 Forbidden: Error=BadAuthentication
Url=[oauth url]
Info=WebLoginRequired
```

If I paste the oauth url in a browser then I can sign in but after signing in it won't continue to anything

**Comment by budkin** [comment]
Oh, sorry, I forgot to mention this in the readme. If you use 2 factor authorisation, you'll have to create an app password on this page https://security.google.com/settings/security/apppasswords

**Comment by budkin** [comment]
Also, it takes a few seconds to create a database with your GPM library

**Comment by MartijnBraam** [comment]
Works great, thanks.
