### ISSUE TITLE
Can't connect to Google Music: no valid devices

### ISSUE THREAD

**Issue by hotice** [budkin/jam#25]
That's the error message I get when trying to login (using the latest version of jam): ``Can't connect to Google Music: no valid devices``. Any ideas?

**Comment by budkin** [comment]
That means you are not using GPM on your phone. No devices means no phones. Currently the GMusic library makes use of GPM mobileclient API, and jam disguises as your phone, so no additional devices added in the list of your devices on GPM. I should have put this in Readme from the beginning, but wasn't sure. If you have no smartphone, I'm afraid you can't use this program. At least at its current state, maybe I'll work on the library and add missing webclient support, I don't know

**Comment by hotice** [comment]
Indeed, I don't for this account, I wanted to use a test account when this happened. Thanks for the info!

**Comment by budkin** [comment]
I added this information to the Readme. May I close this?
And thanks for your article on Webupd8

**Comment by hotice** [comment]
Sure, thank you!
