### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by silvernode** [budkin/jam#28]
Got my GOPATH setup but ever time I use go I'm not sure what's going on. Do I need to make this repository in GOPATH? I just have it set to GOPATH=$HOME/go

**Comment by budkin** [comment]
You just need to `go get` it, assuming your GOPATH is set to $HOME/go

**Comment by hotice** [comment]
@silvernode if you're on Linux, this should help: http://www.webupd8.org/2017/02/jam-listen-to-google-play-music-from.html

**Comment by silvernode** [comment]
working using "go get github.com/budkin/jam"
Maybe put that in the readme? 
Thanks for the help everyone!
