### ISSUE TITLE
Don't write files to the root of the home directory

### ISSUE THREAD

**Issue by MartijnBraam** [budkin/jam#3]
The XDG specification mentions this about data files:

> $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

**Comment by budkin** [comment]
Thanks, I'll fix that and publish a new release tomorrow

**Comment by budkin** [comment]
fixed by @nlamirault, credits to him
