### ISSUE TITLE
Please allow disabling Last.FM scrobbler

### ISSUE THREAD

**Issue by luisnabais** [budkin/jam#31]
Hello.

I have a proxy at work which disables access to last.fm, but allows access to Google Play Music.
I can't use the app (get "Forbidden" error), because of this. Is there a way to disable last.fm scrobbler?

Why the need for last.fm scrobbler? KISS :) Just a Google Play Music app, nothing more.

Thanks

**Comment by budkin** [comment]
Please test the version  from master, if possible

**Comment by luisnabais** [comment]
It worked flawlessly :)

Thanks a lot for your fast answer and solving!
