### ISSUE TITLE
Try to list artists in alphabetical order

### ISSUE THREAD

**Issue by nlamirault** [budkin/jam#5]
When music database is loaded, artists are not listed in an alphabetical order

**Comment by budkin** [comment]
This is a feature, not a bug. Do you need them in order?

**Comment by nlamirault** [comment]
It seems to me that it is easier to read the artists. Like in the web interface of Google Music.

**Comment by budkin** [comment]
Okay, I'll add a "randomize artists" keybinding feature on the TODO list and they will be sorted in alphabetical order by default.

The reasoning behind randomly sorted artists is that I've gotten sick and tired of seeing the same artists in my huge library all over again in the official web version of GPM, that's also why a searching feature was a high priority for me (too bad, it doesn't always work as it should)

**Comment by budkin** [comment]
searching is fixed (hopefully)

**Comment by nlamirault** [comment]
:+1:

**Comment by budkin** [comment]
Thanks for you help, Nicolas. Without it this project wouldn't have been such a success
